### ISSUE TITLE
最新版本获取不了登录短信

### ISSUE THREAD

**Issue by jcl0722** [jerrykuku/luci-app-ttnode#19]
2021年9月4日提交无法获取登录短信。
点击获取短信验证码，无作用。

**Comment by lon91ong** [comment]
+1，遇到了相同的情况
可以试试降级回之前的版本，再重启一下路由器
我这里降级到0.3版能用了

**Comment by jcl0722** [comment]
是的，此版本不能获取登录短信。希望能修复一下！

**Comment by Beginner-Go** [comment]
https://github.com/jerrykuku/luci-app-ttnode/pull/20
can you test?

**Comment by jcl0722** [comment]
fix

> #20 你能测试一下吗？

fix可以正常接收短信与登录。但我发现，输入手机号，点击获取验证码，如果不输入，将进入60秒获取短信验证的循环状态。
